Added support for DPAD, menus and multiple instances of Denon AVR
unfoldedcircle/integration-denonavr pull request #35
Opened 2024-03-16 10:30 UTC by albaintor

Testes successfully on my remote (not through simulator) :

1. Multiple instances management : based on your work on apple TV integration with an intermediate setup flow to add a new device or remove existing device. However I only have one Denon receiver : I was able to start the process to add a new device, it scanned by environment, found my existing device but refused to add the entity as already existing.
2. Adds new commands : direction pad, enter, back, menus (setup and option menus mapped respectively to settings+menu and contexte menu), info

The embedded library is not up to date so I added the commands directly from the avr.py file.
This new commands work fine on my setup (Denon AVR 4700)

2024-03-16 13:44 UTC, klada commented
I think you are using HTTP control for these commands, even if Telnet control was selected in the integration. But thanks for looking into this.

2024-03-16 17:31 UTC, zehnm requested changes
Thanks for enhancing the features!
I'll test the new commands with my Denon AVR this weekend.

Please reach out first when doing bigger changes, see [CONTRIBUTING.md](https://github.com/unfoldedcircle/integration-denonavr/blob/main/CONTRIBUTING.md). Related issues:
- #20 
- #33

This PR needs to be split into multiple pull request: one for additional commands and another for multi-device support.

I highly suggest to create a dedicated branch for each PR in your repo and avoid using the main branch. Rebasing and PR changes become much easier.
Preferrably, a PR should only contain one feature in one commit.

2024-03-16 17:31 UTC, zehnm commented on requirements.txt
> +ucapi==0.1.6
Latest ucapi version is 0.1.7

2024-03-16 17:31 UTC, zehnm commented on requirements.txt
>  denonavr~=0.11.4
Please update denonavr library to latest version before adding custom commands. 0.11.5 has quite a few new features: https://github.com/ol-iver/denonavr/releases

2024-03-16 17:31 UTC, zehnm commented on .idea/misc.xml
Please don't change project files. Applies to all files in .idea directory.

2024-03-16 17:31 UTC, zehnm commented on intg-denonavr/setup_flow.py
Multi-device support belongs in a dedicated pull request, so it can be independently tested and only merged & released when verified.
Before working on a major new feature, please coordinate with us first. Either by opening a new issue or start a discussion in a matching issue. Multi-device support is: #20

2024-03-16 17:51 UTC, albaintor commented on intg-denonavr/setup_flow.py
I didn't find the corresponding issue so directly going for a PR.
Also about the additional commands I found that the modifications were minor to be included on the same PR but I can split in a separate PR if you want

2024-03-17 08:42 UTC, albaintor commented
Hi,
I have made 2 separate PR : this one for multi-instances (and rollbacked there the other changes on additional commands) on the main branch and another one with only the additional commands on a dedicated branch.
And yes I was not used to create branches for PR

About additional commands : I added the 2 modes (telnet and http), whereas only http commands on the previous commit. Tested OK on my setup

2024-03-20 10:02 UTC, albaintor commented
Hi,
I have applied modifications : code formatting check, merged updates from the last release. This PR is ready to be reviewed (multiple instances support)

2024-03-26 08:09 UTC, zehnm commented
Thanks for the updated PR!
I'll review and test it later this week, but it will be a bit tricky with only one network capable receiver.

2024-03-26 08:15 UTC, albaintor commented
> Thanks for the updated PR! I'll review and test it later this week, but it will be a bit tricky with only one network capable receiver.

Hi,
I have only one receiver too however to test it I did the following  : I changed the generated config file by modifying the address and then launched the setup flow again to get a second device & entity.

2024-06-05 06:53 UTC, Kat-CeDe commented
Hi,
if it help I have 1 Denon and 1 Marantz.

Ralf

2025-02-06 14:12 UTC, Kat-CeDe commented
Thank you it is working now:-)

2025-05-01 12:00 UTC, zehnm commented
Closing: new PR #63 with improved configuration handling and duplicate checks

2025-05-01 12:00 UTC, closed without merging