Added additional commands (telnet and http protocols) : DPAD and menus
unfoldedcircle/integration-denonavr pull request #36
Opened 2024-03-17 08:31 UTC by albaintor

This is a separate PR for just the additional commands. The other PR will contain only the multi instances part
Related to https://github.com/unfoldedcircle/integration-denonavr/issues/33

2024-03-17 11:31 UTC, zehnm commented
Great! And thank you for also opening a PR in the denonavr library 👍 
I'll check it later today when I'm back home.

2024-03-18 11:07 UTC, zehnm requested changes
Tested with AVR-X2700H and the new functions work 👍 

Please fix the cosmetic issues, then I'll merge it.

2024-03-18 11:07 UTC, zehnm commented on requirements.txt
> +denonavr~=0.11.5
Is there a reason you only updated denonavr to 0.11.5 and not the latest 0.11.6?

2024-03-18 11:07 UTC, zehnm commented on intg-denonavr/media_player.py
> +            res = await self._receiver.setup()
Both commands call the same function, one feature is enough. MENU is preferred, since it will have preference in auto-mappings. 
Remove `Features.SETTINGS` and the command handler.

2024-03-18 11:07 UTC, zehnm commented on intg-denonavr/avr.py
> +                await self.setup_open()
`async_send_telnet_commands` always returns None! If condition doesn't make sense.

2024-03-18 11:07 UTC, zehnm commented on intg-denonavr/avr.py
> +        """Send previous-track command to AVR."""
Comment doesn't match. Applies to all new methods.

2024-03-18 11:07 UTC, zehnm commented on intg-denonavr/avr.py
> +            await self._receiver.async_send_telnet_commands("MNCUP")
Please invert logic to make it more readable:
```python
        if self._use_telnet:
            await self._receiver.async_send_telnet_commands("MNCUP")
        else:
            await self._receiver.async_get_command(AVR_COMMAND_URL+"?MNCUP")
```
Applies to all new methods.

2024-03-18 11:07 UTC, zehnm commented on intg-denonavr/avr.py
> +AVR_COMMAND_URL="/goform/formiPhoneAppDirect.xml"
Linting issue. See failed check.
Use black to format sources: `black intg-denonavr --verbose --line-length 120 `

2024-03-18 12:31 UTC, albaintor commented on intg-denonavr/avr.py
> +        """Send previous-track command to AVR."""
Done

2024-03-18 12:32 UTC, albaintor commented on intg-denonavr/media_player.py
> +            res = await self._receiver.setup()
ok removed

2024-03-18 12:33 UTC, albaintor commented on requirements.txt
> +denonavr~=0.11.5
No reason, I updated it

2024-03-18 12:34 UTC, albaintor commented on intg-denonavr/avr.py
> +                await self.setup_open()
Indeed, I replaced the telnet command to get the info by the get command in all cases

2024-03-18 12:42 UTC, albaintor commented
All modifications applied, please check for merge

2024-03-18 13:01 UTC, zehnm requested changes
Without the changed files in .idea it's ok.

2024-03-18 13:01 UTC, zehnm commented on .idea/integration-denonavr.iml
Please don't commit project configuration files. Applies to .idea directory.

2024-03-18 13:08 UTC, albaintor commented on .idea/integration-denonavr.iml
I reverted it but my IDE (pycharm CE)  changed it again .... done

2024-03-18 13:21 UTC, zehnm commented on .idea/misc.xml
I'll revert this once merged. Python 3.11 is required to embedd it in the R2 firmware.

2024-03-18 13:22 UTC, zehnm approved these changes
Thanks for the enhancement! I'll create a new release and include it in the next firmware release.

2024-03-18 13:23 UTC, merged