Improved reconnection delay
unfoldedcircle/integration-denonavr pull request #49
Opened 2024-12-16 20:24 UTC by albaintor

I disabled the setup call during (re)connection when it has already been done once.
I also updated the requirements (denonavr library in particular)

2024-12-16 20:34 UTC, albaintor commented
I also updated pyee requirement but I realized maybe I shouldn't as you mentioned limits with pylint

2024-12-17 08:19 UTC, albaintor commented
Update : I have tested the fix on my setup and it working. I was worried that the setup call was always necessary after disconnect but this is not the case. I have mocked a script to test : 1/ connect, 2/disconnect, 3/connect again, and I still have the events (volume change, input source changed....)

2024-12-18 21:48 UTC, zehnm requested changes
Thanks for the PR. I only did a code review so far and I'll test the reconnection behaviour tomorrow.

There are a lot of changes which don't seem related to this PR's description.
I thought this is mainly to avoid calling `async_setup()` after a reconnect, but the other changes are not explained why they are required. For example removing the lock or changing volume handling.
Also the `power_toggle` method is still used and may not be removed.

2024-12-18 21:48 UTC, zehnm commented on intg-denonavr/avr.py
> -            await self._receiver.async_get_command(url)
What was the reason to remove this method and duplicate it 10 times?

2024-12-18 21:48 UTC, zehnm commented on intg-denonavr/avr.py
> +        self._expected_volume = min(self._expected_volume + VOLUME_STEP, 100)
Doesn't this ignore now the user configurable volume step?
- `self._volume_step` should contain the configured step from the setup flow
- `VOLUME_STEP` is a constant

2024-12-18 21:48 UTC, zehnm commented on intg-denonavr/avr.py
> +        self.events.emit(Events.UPDATE, self.id, {MediaAttr.VOLUME: self._expected_volume})
Please explain the volume logic change and removing the `_update_lock`.
This PR is about the reconnection delay. If that's not related, then please open a separate PR.

2024-12-18 21:48 UTC, zehnm commented on intg-denonavr/avr.py
> -
This method is still used!
https://github.com/unfoldedcircle/integration-denonavr/blob/main/intg-denonavr/media_player.py#L247-L248

2024-12-19 06:13 UTC, albaintor commented
Sorry I messed up with the merge I committed experimental changes. This is reverted now

2024-12-19 22:13 UTC, zehnm commented
Thanks for reverting the other changes. I'll start testing it tomorrow and look into the `receiver.async_setup()` function, if there could be any side-effects if not called at reconnect.

2024-12-20 06:35 UTC, albaintor commented
Normally there shouldn't be: I have mocked and tested the reconnection but a second look is useful

2024-12-22 18:11 UTC, zehnm commented
Looking at the code of the denonavr library, it seems safe to skip the `async_setup` call during reconnect and only call `async_update`. If setup is required, it will automatically be called:

https://github.com/ol-iver/denonavr/blob/72294567cd35904e7b5ee68595f577eea603ce66/denonavr/denonavr.py#L137-L169

I still need to test it with my receiver.

2024-12-23 16:16 UTC, zehnm approved these changes
LGTM 👍

2024-12-23 16:17 UTC, merged